var t = [
  {
    name: _language[_curLang].publicCloud,
    selected: false,
    checked: false,
    open: false,
    renaming: false,
    selecting: false,
    operations: ['Create New', 'Property'],
    guid: '86023a7e3f2646a2bbee8a9fec7e6bcb',
    path: _rootPath + '/MaterialList',
    floor: 1,
    type: "folder",
    children: []
  },
  {
    name: 'TranshCan',
    selected: false,
    checked: false,
    open: false,
    renaming: false,
    selecting: false,
    operations: ['Property', 'Restore All Materials', 'Empty Trash Can'],
    guid: 0,
    path: _rootPath + '/TranshCan',
    floor: 1,
    type: "folder",
    children: []
  },
  {
    name: _language[_curLang].searchResult,
    selected: false,
    checked: false,
    open: false,
    selecting: false,
    operations: ['Property'],
    guid: 1,
    path: _rootPath + '/Search Result',
    floor: 1,
    type: "folder",
    children: [],
    searchResult: []
  }
];
const state = {
  userDept: [],
  dragSymbol: false,
  navPath: [],
  nodes: t,
  selectedMaterials: [],
  signIndex: 0,
  sortType: 'title',
  sortSymbol: true,
  typeSymbol: false,
  mousePosition: {
    x: 0,
    y: 0
  },
  menuStatus: false,
  dragData: {
    left: 0,
    top: 0,
    width: 0,
    height: 0
  },
  clipBoard: [],
  clipBoardSymbol: true, //true 为剪贴， false为复制
  userInfo: {
    loginName: '',
    nickName: '',
    userCode: ''
  },
  svplayerStatus: false,
  resourceBlockStatus: true,
  alwaysGet: false,
  thumbPadding: 7,
  saveFolder: {},
  listOrder: {
    type: 'title',
    symbol: true,
  },
  dict: _language[_curLang],
  selectedNode: null,
  eventArray: {},
  previewBaseUrl: golbalSetting.CM + '/ModulePage/webpreview.html',
  previewUrl: golbalSetting.CM + '/ModulePage/webpreview.html?type=32',
  propertyBaseUrl: golbalSetting.CM + '/ModulePage/webpreview.html',
  propertyUrl: golbalSetting.CM + '/ModulePage/webproperties.html',
  headers: [
    {
      name: _language[_curLang].title,
      attr: 'name',
      width: 200,
      dragging: false,
      checked: true,
    },
    {
      name: _language[_curLang].creator,
      attr: 'creatorName',
      width: 100,
      dragging: false,
      checked: true,
    },
    {
      name: _language[_curLang].creationDate,
      attr: 'formatDate',
      width: 130,
      dragging: false,
      checked: true,
    },
    {
      name: _language[_curLang].modifiedBy,
      attr: 'modifierName',
      width: 100,
      dragging: false,
      checked: true,
    },
    {
      name: _language[_curLang].modificationDate,
      attr: 'modificationDate',
      width: 130,
      dragging: false,
      checked: true,
    },
    {
      name: _language[_curLang].clipStatus,
      attr: 'clipStatus',
      width: 100,
      dragging: false,
      checked: true,
    },
    {
      name: _language[_curLang].storageStatus,
      attr: 'onlinstatus',
      width: 100,
      dragging: false,
      checked: true,
    },
    {
      name: _language[_curLang].hv,
      attr: 'hv',
      width: 50,
      dragging: false,
      checked: true,
    },
    {
      name: _language[_curLang].lv,
      attr: 'lv',
      width: 50,
      dragging: false,
      checked: true,
    },
    {
      name: _language[_curLang].ha,
      attr: 'ha',
      width: 100,
      dragging: false,
      checked: true,
    },
    {
      name: _language[_curLang].la,
      attr: 'la',
      width: 50,
      dragging: false,
      checked: true,
    },
    {
      name: _language[_curLang].totalDuration,
      attr: 'totalDuration',
      width: 100,
      dragging: false,
      checked: true,
    },
    {
      name: _language[_curLang].length,
      attr: 'length',
      width: 100,
      dragging: false,
      checked: true,
    },
    {
      name: _language[_curLang].inPoint,
      attr: 'trimin',
      width: 100,
      dragging: false,
      checked: true,
    },
    {
      name: _language[_curLang].outPoint,
      attr: 'trimout',
      width: 100,
      dragging: false,
      checked: true,
    },
    {
      name: _language[_curLang].sd,
      attr: 'img16_9sd',
      width: 80,
      dragging: false,
      checked: true,
    },
    {
      name: _language[_curLang].rights,
      attr: 'rights',
      width: 150,
      dragging: false,
      checked: true,
    },
    {
      name: _language[_curLang].description,
      attr: 'comments',
      width: 200,
      dragging: false,
      checked: true,
    },
    {
      name: _language[_curLang].toBeDel,
      attr: 'tobedel',
      width: 110,
      dragging: false,
      checked: true,
    },
    {
      name: _language[_curLang].hdsd,
      attr: 'hsd',
      width: 70,
      dragging: false,
      checked: true,
    },
  ]
}
